### PR TITLE
Support interface's metering config

### PR DESCRIPTION
**Pull request by byteocean**

### CODE REVIEW

**Review by guvenc — CHANGES_REQUESTED** [review]
@byteocean 
Looks good. Could you please enhance the test case for creating the interface function in a way that the new introduced parameters in create/get interface call will be set and retrieved. (So automatically tested)

The test part should be in "When using interface functions" -> "should create successfully"

Thanks.

**Comment by byteocean** [comment]
It is a bit tricky to have positive tests as other interface's specs. it is because, the actual configuration will be ignored if the device type is TAP currently on the dp-service side. What currently in code is that, without explicitly specifying some metering values that are greater than 0, the interface should be created successfully and 0 values are returned when getting interface information.

**Comment by guvenc** [comment]
Yeah, I agree it is tricky to test it with TAP device when it is completely ignored.

**Review by guvenc — APPROVED** [review]
Looks good.

**Pull request merged**
